### ISSUE TITLE
Description too long.

### ISSUE THREAD

**Issue by Laspante** [Darkhax-Minecraft/Enchantment-Descriptions#134] opened 2022-07-25 10:36 UTC
So basically the issue is that the description is too long. When u go on the book the description is too long and go over the edge of the screen, imma leave a screenshot. It would we nicer if instead of being just long the descruption go down, idk if u understood. 
![Screenshot 2022-07-25 123249](https://user-images.githubusercontent.com/78699919/180757592-9106c535-22c2-445a-ae3c-9db591633e69.png)

**Comment by Darkhax** [comment] 2022-07-25 18:19
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-07-25 18:19 UTC
