### ISSUE TITLE
Description text not wrapping

### ISSUE THREAD

**Issue by Gabbleducky** [Darkhax-Minecraft/Enchantment-Descriptions#116] opened 2022-04-22 21:06 UTC
![image](https://user-images.githubusercontent.com/19570864/164793331-49ed5f87-d8c7-41f1-b765-f539a8679d16.png)

As can be seen in the image above, the description for some enchantments is so long that it disappears off the edge of the screen if you have the recipe book open. 

Could you add some sort of text wrapping or second line to some of the longer descriptions to prevent this?

**Comment by Gabbleducky** [comment] 2022-04-22 21:10
![image](https://user-images.githubusercontent.com/19570864/164793797-a1d5ea33-9531-4e46-89c3-8eb57e8acf3e.png)

This also happens when looking at books/items in a chest.

v 10.0.2

Fabric v 0.51.1

**Comment by Darkhax** [comment] 2022-04-22 21:14
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-04-22 21:14 UTC
