### ISSUE TITLE
Descriptions Too Long for Screen

### ISSUE THREAD

**Issue by MrRoooo** [Darkhax-Minecraft/Enchantment-Descriptions#87] opened 2021-12-11 14:25 UTC
There some descriptions that are too long for screen that will get cut off.

Example: on screen format

![image](https://user-images.githubusercontent.com/7705035/145680009-aec16dfa-310b-42ce-9e26-def7f1ff3696.png)

Example: off screen format

![image](https://user-images.githubusercontent.com/7705035/145680052-e114737b-54c3-43ad-b664-40af7168b228.png)

**Comment by Darkhax** [comment] 2021-12-11 14:27
This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2021-12-11 14:27 UTC

**Comment by MrRoooo** [comment] 2021-12-11 14:28
Thanks for the fast reply and fix!
