### ISSUE TITLE
Text won't wrap

### ISSUE THREAD

**Issue by Reimirno** [Darkhax-Minecraft/Enchantment-Descriptions#126] opened 2022-06-20 23:05 UTC
When the description text is too long it won't wrap so basically the tooltip is cut off and it is very difficult, sometimes impossible, to see the whole tooltip.

**Comment by Darkhax** [comment] 2022-06-20 23:23
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-06-20 23:23 UTC
