### ISSUE TITLE
Text being cut

### ISSUE THREAD

**Issue by Pixelum42** [Darkhax-Minecraft/Enchantment-Descriptions#186] opened 2023-03-16 21:09 UTC
The text description is so long that when it shows the to left, it's just cut by the screen limit and i see half of the description.
I think there's a way to direct the text to the right or left when text's window is cut !

**Comment by Pixelum42** [comment] 2023-03-16 21:10
![image](https://user-images.githubusercontent.com/91870812/225753437-ad242bfd-bc8c-401c-8d9e-938409b31422.png)

**Comment by Darkhax** [comment] 2023-03-16 23:38
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2023-03-16 23:38 UTC

**Comment by Pixelum42** [comment] 2023-03-17 12:30
Wow thank you ! Sorry for late reply I was not expecting you to answer this fast. The TooltipFix mod works perfectly thank you !
