### ISSUE TITLE
Long Descriptions go off screen

### ISSUE THREAD

**Issue by BurntTrashFor** [Darkhax-Minecraft/Enchantment-Descriptions#181] opened 2023-01-28 16:22 UTC
Modded enchantments with long descriptions can go offscreen because it some doesn't go down. 
![image](https://user-images.githubusercontent.com/114228376/215277441-d6abf1ab-fe7e-4fe5-9d08-86815acc0306.png)
Fabric 13.0.14

**Comment by Darkhax** [comment] 2023-01-29 14:39
I've been outsourcing this to the [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix) mod, although this has been a huge source of issue reports for me so a Fabric level patch would be preferred. 

Duplicate of #60

**Closed as completed by Darkhax** 2023-01-29 14:39 UTC
