### ISSUE TITLE
Infoboxes pushed off the edge of the screen

### ISSUE THREAD

**Issue by chloebarber** [Darkhax-Minecraft/Enchantment-Descriptions#88] opened 2021-12-11 21:24 UTC
Minecraft 1.18 / Fabric

See attached screenshot. Long enchantment descriptions, even vanilla ones, extend the infobox off to the left of the screen, rendering it illegible. This happens both windowed and fullscreen, and occurs in all menus (crafting menu, inventory menu, enchanting menu, etc).

The screen this screenshot is taken on is 1440p

Installed UI mods are pretty basic:
Roughly Enough Items
InventoryHUD+
AppleSkin

Full modlist is also attached
![modlist](https://user-images.githubusercontent.com/31894087/145692066-7f0ee3b7-09ce-4876-aa2d-8e232f129fee.PNG)
![enchantmentdescriptions](https://user-images.githubusercontent.com/31894087/145692068-0c8d31ea-1c30-4a04-a4b1-d4089176cfb6.PNG)

**Comment by Darkhax** [comment] 2021-12-12 12:03
This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2021-12-12 12:03 UTC
