### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by Fiopon** [Darkhax-Minecraft/Enchantment-Descriptions#78] opened 2021-09-15 16:40 UTC
Please allow for line breaks in enchantment descriptions. It would help a lot, since a lot of the enchantment tooltips go off-screen for me, and using `\n` in the lang file results in this:
![image](https://user-images.githubusercontent.com/56209751/133474353-077211d6-aaff-4579-8534-7ad5d79b4d6f.png)

**Comment by Darkhax** [comment] 2021-09-15 21:46
This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2021-09-15 21:46 UTC
