### ISSUE TITLE
Overflowing textbox

### ISSUE THREAD

**Issue by JonneSaloranta** [Darkhax-Minecraft/Enchantment-Descriptions#128] opened 2022-07-03 18:40 UTC
Item name is overflowing off the screen cutting part of the textbox off

![image](https://user-images.githubusercontent.com/72470168/177052886-2804b730-59b4-4b2e-ae34-62e05e848c09.png)
![image](https://user-images.githubusercontent.com/72470168/177052963-583fbf6e-73bb-4316-95f3-0f007f63db48.png)

Version 1.19
I'm using sodium if that matters

**Comment by Darkhax** [comment] 2022-07-03 19:40
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-07-03 19:40 UTC
