### ISSUE TITLE
[Fabric 1.19.2] Enchantment Description does not wrap tooltip text

### ISSUE THREAD

**Issue by TelepathicGrunt** [Darkhax-Minecraft/Enchantment-Descriptions#169] opened 2022-11-25 17:09 UTC
On Forge, Forge added a patch to wrap tooltip descriptions. However, on Fabric, this patch does not exist which causes the below picture to occur. Some of the vanilla enchantment descriptions provided by Enchantment Descriptions also goes offscreen without any other mods on.

Forge:
![image](https://user-images.githubusercontent.com/40846040/204030969-1d58cb79-0bf1-4d7c-bafe-133467eebbbf.png)

Fabric:
![image](https://user-images.githubusercontent.com/40846040/204030951-9c1a495b-3032-448a-9979-26ab0a64b1ce.png)

Fabric API does have an issue report asking for the automatic wrapping so you could either try and do wrapping yourself now or wait and see if Fabric API will get around to it soon. https://github.com/FabricMC/fabric/issues/2283

**Comment by Darkhax** [comment] 2022-11-25 20:45
I've been outsourcing this to the [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix) mod, although this has been a huge source of issue reports for me so a Fabric level patch would be preferred. 

Duplicate of #60

**Closed as completed by Darkhax** 2022-11-25 20:45 UTC
