### ISSUE TITLE
Not fitting the screen right

### ISSUE THREAD

**Issue by xVeith** [Darkhax-Minecraft/Enchantment-Descriptions#114] opened 2022-04-12 11:55 UTC
1.18.2, Fabric
Does this only happen to me or it is a known issue? Trying to fix it but no clue what is the root of it, works just fine on Forge tho
![image](https://user-images.githubusercontent.com/48566070/162956285-b30798a5-9e2b-46ab-bd92-80107f9fd237.png)

**Comment by Darkhax** [comment] 2022-04-12 17:19
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-04-12 17:19 UTC
