### ISSUE TITLE
[Suggestion] Linebreak for long texts

### ISSUE THREAD

**Issue by quiqueck** [Darkhax-Minecraft/Enchantment-Descriptions#139] opened 2022-07-30 23:05 UTC
Often, the description of Enchants is quite long, making them impossible to read on smaller screens. Due to the alignment of the tooltip, the actual name of the enchantment is often displayed outside the screen.
![Bildschirmfoto 2022-07-31 um 01 01 05](https://user-images.githubusercontent.com/280847/182002925-2996293d-0827-4554-938e-5571d499a2a5.png)

This could be solved by either forcing the line start to be always inside the screen bounds (so that we can always read the enchantment name) or by simply line breaking the description if it get's bigger than the screen.

**Comment by Darkhax** [comment] 2022-07-31 05:40
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-07-31 05:40 UTC
