### ISSUE TITLE
Text Wrap?

### ISSUE THREAD

**Issue by PhantomHT1320** [Darkhax-Minecraft/Enchantment-Descriptions#81] opened 2021-10-21 07:31 UTC
When im looking at a longer description, all the text is 1 line and because the descrip is so long the first few words or 1/2 the description is off screen/unreadable. can you make it so the text wraps and displays X amount of words/characters per line

![2021-10-21_00 29 38](https://user-images.githubusercontent.com/92912607/138231643-8769bc16-28b2-4357-87c7-4659fa1fec68.png)
?

**Comment by Darkhax** [comment] 2021-10-21 07:35
This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2021-10-21 07:35 UTC
