### ISSUE TITLE
Add a scrollbar and a max-width

### ISSUE THREAD

**Issue by zeid0ne** [Darkhax-Minecraft/Enchantment-Descriptions#120] opened 2022-06-08 15:49 UTC
I have an issue when a lot of text is shown :

![image](https://user-images.githubusercontent.com/38461940/172660947-acd4f468-9692-46e6-af03-a060f3521eef.png)

Add a scrollbar and a max-width to the tooltip could save the problem i think.

**Comment by Darkhax** [comment] 2022-06-08 17:45
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-06-08 17:45 UTC
