### ISSUE TITLE
Display issue using the librarian interface

### ISSUE THREAD

**Issue by nuckpio** [Darkhax-Minecraft/Enchantment-Descriptions#108] opened 2022-03-19 15:19 UTC
Hi,
I installed your mod today on fabric 1.18.2 (v10.0.2).
I was trying to reset a librarian villager to obtain a specific enchantment book. The problem is, the description box is displayed from our mouse pointer through the left side of the screen, which does not give us the ability to read the enchantment name. also I see just the last part of the description ("[...] such as zombies and skeletons", "[...]thing bolts during thunderstorms") the first part is on the left of the screen.
I hope my description of the issue is clear, my English is not perfect (you know french people are not the bests English talkers in the world 😆)
I would be pleased to show you the problem if needed.
Thanks for this mod.
regards.

**Comment by Darkhax** [comment] 2022-03-20 10:44
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-03-20 10:44 UTC
Labels: duplicate
