### ISSUE TITLE
Some descriptions do not fit on the screen

### ISSUE THREAD

**Issue by ScoobyVI** [Darkhax-Minecraft/Enchantment-Descriptions#98] opened 2022-01-11 21:52 UTC
Hi! Love this mod, but some of the enchantments have descriptions so long they don't fit on the screen and spill off the side

Is there a way around this?

Thanks

![2022-01-11_21 48 21](https://user-images.githubusercontent.com/97412385/149027058-a59e67a4-f0fb-4db3-9d55-b36094d40dd5.png)
n

**Comment by Darkhax** [comment] 2022-01-11 21:59
This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-01-11 21:59 UTC
Labels: duplicate

**Comment by ScoobyVI** [comment] 2022-01-11 22:14
Thanks a lot, sorry - I had no idea there was a third party fix
