### ISSUE TITLE
issue with description lengths on fabric 1.19

### ISSUE THREAD

**Issue by Aikirob** [Darkhax-Minecraft/Enchantment-Descriptions#137] opened 2022-07-29 02:34 UTC
the description length is so long it goes off screen and i cant read it, needs to be able to take a new line so it stays on screen.

**Comment by Darkhax** [comment] 2022-07-29 06:19
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-07-29 06:19 UTC
