### ISSUE TITLE
Enchantments go off the screen

### ISSUE THREAD

**Issue by HoodBlah** [Darkhax-Minecraft/Enchantment-Descriptions#77] opened 2021-09-09 21:45 UTC
Fabric 1.17.1, when hovering over an enchantment the description and name go off the side of the screen if its long.

**Comment by Darkhax** [comment] 2021-09-09 21:51
Hello,

This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2021-09-09 21:51 UTC
Labels: duplicate
