### ISSUE TITLE
made half of string to transfer if description is long

### ISSUE THREAD

**Issue by BoBkiNN** [Darkhax-Minecraft/Enchantment-Descriptions#106] opened 2022-03-07 07:09 UTC
example:
`"some desc but it looooooooooooooooong, but i need to make this text long for example"` -->
`"some desc but it looooooooooooooooong,\n
 but i need to make this text long for example"`

**Comment by Darkhax** [comment] 2022-03-07 08:11
This is a vanilla bug. Tooltips should automatically wrap to the length of your screen. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix). Hardcoding this is a bad idea as it will not be consistent across different monitor sizes and GUI scales. 

Duplicate of #60

**Closed as completed by Darkhax** 2022-03-07 08:11 UTC
