### ISSUE TITLE
Cropped, perhaps add a break line? Or adaptive text?

### ISSUE THREAD

**Issue by Psychodeus** [Darkhax-Minecraft/Enchantment-Descriptions#160] opened 2022-10-06 23:15 UTC
![image](https://user-images.githubusercontent.com/93028949/194434978-7a5bd6ed-8a5e-40cf-9a3f-6ca4484b2924.png)

GUI Scale : 2

**Comment by Psychodeus** [comment] 2022-10-06 23:16
![image](https://user-images.githubusercontent.com/93028949/194435232-770a96e8-fa3d-44e5-864f-3914ab7f6191.png)

**Comment by Darkhax** [comment] 2022-10-06 23:53
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-10-06 23:53 UTC
