### ISSUE TITLE
Enchant name no readable

### ISSUE THREAD

**Issue by kalixdrake** [Darkhax-Minecraft/Enchantment-Descriptions#113] opened 2022-04-11 00:24 UTC
If the enchant descripcion is too long, the text box just get out of the screen attemping to show all the content of the description, what does not let read the enchanment description

**Comment by Darkhax** [comment] 2022-04-11 03:03
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-04-11 03:03 UTC
