### ISSUE TITLE
Enchantment descriptions make the tooltip cut off.

### ISSUE THREAD

**Issue by d4rkm0nkey** [Darkhax-Minecraft/Enchantment-Descriptions#73] opened 2021-06-24 16:32 UTC
Enchantment descriptions make the tooltip cut off, because the tooltip gets to big. I think you should add line breaks into the enchanment descriptions.

![2021-06-24_18 29 04](https://user-images.githubusercontent.com/19959176/123299949-519c5d00-d51a-11eb-90dd-efd6c4228a2a.png)

**Comment by d4rkm0nkey** [comment] 2021-06-24 16:33
Or position the tootltip so it is fully shown on the screen. Like this I can't even read the enchantment name.

**Comment by Darkhax** [comment] 2021-06-24 18:53
Duplicate of #60 #66 #67 

This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

**Closed as completed by Darkhax** 2021-06-24 18:53 UTC
