### ISSUE TITLE
Text going off screen

### ISSUE THREAD

**Issue by CosmiChaos** [Darkhax-Minecraft/Enchantment-Descriptions#115] opened 2022-04-16 18:59 UTC
I'm having some issues with the descriptions going off-screen, making them unreadable. This happens with both vanilla Minecraft enchantment descriptions and modded ones. Is there a way to make the description boxes vertically longer for long descriptions/ make them stop going off-screen? (This happens both in the inventory screen and when trying to buy enchanting books from librarians). I'm on 18.1 using EnchantmentDescriptions-Fabric-1.18.1-9.0.13

Here are some screenshots I pulled from my game

![Uploading Minecraft_ 1.18.1 - Multiplayer (3rd-party Server) 4_16_2022 2_50_48 PM.png…]()
![Minecraft_ 1 18 1 - Multiplayer (3rd-party Server) 4_16_2022 2_50_09 PM](https://user-images.githubusercontent.com/103852371/163687906-db74cd3a-62f9-411b-aa98-72d44158026b.png)
![Minecraft_ 1 18 1 - Multiplayer (3rd-party Server) 4_16_2022 2_52_53 PM](https://user-images.githubusercontent.com/103852371/163687910-0a101c04-52c3-4366-a871-a150dee8abea.png)

**Comment by Darkhax** [comment] 2022-04-16 20:02
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2022-04-16 20:02 UTC
