### ISSUE TITLE
[BUG] Descriptions too long for UI

### ISSUE THREAD

**Issue by Oliver-Habersetzer** [Darkhax-Minecraft/Enchantment-Descriptions#183] opened 2023-02-19 00:47 UTC
Hello there!

First off - thanks for this mod - I rly like it!
But some descriptions are too long for the UI and clip outside of the screen's range.
![image](https://user-images.githubusercontent.com/42864929/219905679-a05ae267-06b0-44b5-abf0-87009815ec36.png)

I'm not sure if this is a bug or if it's expected behavior - however I am playing on a custom modded server with a few friends of mine and all of them have the same issue.

My screen: 2560x1440
Windows scaling: 225%
Minecraft UI scale: 4

It would be nice to at least ensure that the tooltip never exceeds the bounds of the screen.
Ideally there would be some way to auto wrap the description, but that's not easy of course.

I hope this helps - feel free to reach out if you need more info than that.

Cheers!

**Comment by Witheredpicaxe** [comment] 2023-02-19 03:04
im having the same issue, love the mod, just doesnt fit the screen

**Comment by Darkhax** [comment] 2023-02-19 06:04
@Oliver-Habersetzer @Witheredpicaxe 

Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2023-02-19 06:04 UTC

**Comment by Oliver-Habersetzer** [comment] 2023-02-19 16:01
Oh I'm sorry for the duplicate :/
But thank you so much for the help, the mod fixed the issues <3
Much love!
