### ISSUE TITLE
Descriptions too long

### ISSUE THREAD

**Issue by Bunn13** [Darkhax-Minecraft/Enchantment-Descriptions#194] opened 2023-05-15 06:49 UTC
With some enchant descriptions, they're too long, making me unable to see the actual enchants, durability, etc. This issue mainly seems to occur with other mods though; I'll add a screenshot.
![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/133633391/29c7658c-832d-49fa-bdd7-9160324064ec)

**Comment by Darkhax** [comment] 2023-05-15 19:17
This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60

**Closed as completed by Darkhax** 2023-05-15 19:17 UTC
